#!/usr/bin/env bash
# installing and configuring NGINX web server

sudo apt-get -y update
sudo apt-get -y install nginx

# allowing nginx on firewall
sudo ufw allow 'Nginx HTTP'

# Creating new index and redirecting to another page
echo -e "Hello World!" | dd status=none of=/var/www/html/index.nginx-debian.html
sudo sed -i '/^}$/i \ \n\tlocation \/redirect_me {return 301 https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4;}' /etc/nginx/sites-available/default

# starting nginx
sudo service nginx start
