#!/usr/bin/env bash
# Double the number of webservers
sudo apt update
sudo apt install haproxy -y
sh -c echo "\nlisten myserver\n\tbind *:80\n\tbalance roundrobin\n\tserver server1 34.203.77.76:80 check\n\tserver server2 54.157.157.60:80 check\n" >> /etc/haproxy/haproxy.cfg
service haproxy restart
