#!/usr/bin/env bash
# displays a list of currently running processes.
# shows all processes for all users including those which might not have a TTY
# Display in a user-oriented format
# Show process hierarchy

ps -auxf
